//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFNIK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        public int PCID { get; set; }
        public string Processor { get; set; }
        public string VideoCard { get; set; }
        public string MotherBoard { get; set; }
        public string RAM { get; set; }
        public string SSD { get; set; }
        public string HDD { get; set; }
        public string Power { get; set; }
    }
}
